### ISSUE TITLE
My Submission

### ISSUE THREAD

**Issue by kaitogoto7** [mberk/rss-wwc-2023-prediction-competition#2]
@mberk Hello, I have made a submission through an email titled “ Kaito Goto - RSS Women's World Cup 2023 Prediction Competition”. Can I please confirm if the submission file can be extracted from the zip file properly on your side?

**Comment by mberk** [comment]
Hi @kaitogoto7. Apologies for the late reply but it looks like your submission file is fine and you can see yourself included in the recently added leaderboard
